exports.defaultSettings = {
  lastUpdateCheck: new Date().getTime(),
  shortcutOpenMagnifierKeys: ["Control", "i"],
  shortcutOpenHistoryKeys: ["Control", "Shift", "d"],
  shortcutOpenMagnifier: true,
  launchOnStartup: true,
  playSounds: true,
  isHistoryLimit: false,
  showPickedColor: true,
  shortcutMoveLensRightKeys: ["ArrowRight"],
  shortcutMoveLensRight: true,
  shortcutMoveLensDownKeys: ["ArrowDown"],
  shortcutMoveLensDown: true,
  shortcutMoveLensLeftKeys: ["ArrowLeft"],
  shortcutMoveLensLeft: true,
  shortcutMoveLensUpKeys: ["ArrowUp"],
  shortcutMoveLensUp: true,
  shortcutMoveLensRight10pxKeys: ["Shift", "ArrowRight"],
  shortcutMoveLensRight10px: true,
  shortcutMoveLensDown10pxKeys: ["Shift", "ArrowDown"],
  shortcutMoveLensDown10px: true,
  shortcutMoveLensLeft10pxKeys: ["Shift", "ArrowLeft"],
  shortcutMoveLensLeft10px: true,
  shortcutMoveLensUp10pxKeys: ["Shift", "ArrowUp"],
  shortcutMoveLensUp10px: true,
  shortcutIncreaseSizeKeys: ["+"],
  shortcutIncreaseSize: true,
  shortcutDecreaseSizeKeys: ["-"],
  shortcutFormatNext: true,
  shortcutFormatNextKeys: ["Alt", "ArrowRight"],
  shortcutFormatPrevious: true,
  shortcutFormatPreviousKeys: ["Alt", "ArrowLeft"],
  shortcutDecreaseSize: true,
  shortcutOpenHistory: true,
  historyLimit: "30",
  colorProfile: "default",
  createNewPaletteOnPick: true,
  pollingRate: 0,
  quickPicking: true
};
